name: jump_to_item_listview

description: A Flutter project with with an integration of the flutter_list_navigator (jump_to_item) package we developed. 
  This demonstrates the functionality of the package.  
  When a alphabet is clicked, the listview jumps to the first item beginning with that particular alphabet.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_list_navigator:
    path: '../'
#    git:
#      url: git@github.com:kenresoft/flutter_list_navigator.git
#      ref: master
  fontresoft:
    git:
      url: git@github.com:kenresoft/fontresoft.git
      ref: release
  extensionresoft:
    git:
      url: git@github.com:kenresoft/extensionresoft.git
      ref: master
  cupertino_icons: ^1.0.6
  go_router: ^13.1.0
  flutter_riverpod: ^2.4.10
  english_words: ^4.0.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
